certmanager-issuer:
  email: "devops+gitlab@uis.cam.ac.uk"

global:
  minio:
    enabled: false

  psql:
    host: "${db_proxy_service}"

    password:
      secret: "${db_password_secret}"
      key: "${db_password_key}"

    database: "${db_name}"
    username: "${db_username}"

gitlab:
  gitaly:
    persistence:
      storageClass: "${storage_class}"

redis:
  persistence:
    storageClass: "${storage_class}"

gitlab-runner:
  install: false

postgresql:
  install: false
